### ISSUE TITLE
官网演示独立式sender异常

### ISSUE THREAD

**Issue by wanghui2021** [ant-design/x#207]
### 重现步骤

在线示例链接：（必填）
https://x.ant.design/docs/playground/independent-cn
步骤：
1. 在输入框输入一端文字
2. 删除所有的问题
3.

### 当前行为

无法删除输入的第一个字符

### 预期行为

可以清空输入框

### 上下文

可能与下图代码相关
<img width="532" alt="image" src="https://github.com/user-attachments/assets/36d3a824-f0d3-4e59-b10c-2a68b5ef518d">

### 版本

1.0.0

**Comment by YumoImer** [comment]
fixed, thanks~
