### ISSUE TITLE
I can not delete the first letter of Demo

### ISSUE THREAD

**Issue by li-jia-nan** [ant-design/x#208]
### 重现步骤

在线示例链接：（必填）

https://x.ant.design/docs/playground/independent-cn
![image](https://github.com/user-attachments/assets/6dc0594a-3bc2-48e8-8b7d-3016588efee1)

### 当前行为

不能删除第一个字

### 预期行为

可以删除第一个字

### 版本

1.0.0

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
fixed, thanks~
