### ISSUE TITLE
和pro-chat的优势在哪儿？

### ISSUE THREAD

**Issue by ranwawa** [ant-design/x#232]
### 需求动机

目前自研了一套聊天界面，想切换到开源项目上来，peterchat使用的是pro-chat。我们x相对于它来说的优势在哪里呢？或者相对于其它的一些开源项目的优势在哪里呢？感谢

**Comment by zombieJ** [comment]
ProChat 就是 x 的前生，没有竞争关系哈~~~

另外，关于 petercat。 @xingwanying 好升级了~
