### ISSUE TITLE
playground 里左右两边贴在一起了

### ISSUE THREAD

**Issue by afc163** [ant-design/x#235]
https://x.ant.design/docs/playground/independent-cn

<img width="171" alt="图片" src="https://github.com/user-attachments/assets/523901d4-97a0-41be-be06-1c098ddd9d40">

右边也是

<img width="231" alt="图片" src="https://github.com/user-attachments/assets/94d6bcd8-aed4-4331-a915-4f0002ec374c">

**Comment by YumoImer** [comment]
好的，我将处理这个问题。

**Comment by afc163** [comment]
<img width="895" alt="图片" src="https://github.com/user-attachments/assets/917b7941-df6b-42a1-bbcd-1c4f17ee9edc">

溢出了，这个 playground 页面能不能单独定制一下，不需要边栏和 demo 框，直接全页展示。类似 https://ant.design/theme-editor-cn 的效果。

**Comment by YumoImer** [comment]
> <img width="895" alt="图片" src="https://github.com/user-attachments/assets/917b7941-df6b-42a1-bbcd-1c4f17ee9edc">
> 
> 
> 
> 溢出了，这个 playground 页面能不能单独定制一下，不需要边栏和 demo 框，直接全页展示。类似 https://ant.design/theme-editor-cn 的效果。

对，我也在考虑这个。不过切换样板间的方式我和设计师对一下。
