### ISSUE TITLE
Role-角色设计-真实一致 界面有两张PPT重复了

### ISSUE THREAD

**Issue by shanggqm** [ant-design/x#245]
### 重现步骤

在线示例链接：（必填）
https://x.ant.design/docs/spec/authentic-consistent
步骤：
<img width="1612" alt="image" src="https://github.com/user-attachments/assets/55b8b93a-6705-4953-9404-88422fdab387">

### 当前行为

两张PPT重复了，不知道是否刻意为之？

### 版本

1.0.0

**Comment by YumoImer** [comment]
这是搬运文档过程中的 bug，感谢指出。

**Comment by YumoImer** [comment]
有兴趣帮助修复吗 😄

这是第二点中插图的链接：

https://mdn.alipayobjects.com/huamei_iwk9zp/afts/img/A*Ao8DSZhMfIAAAAAAAAAAAAAADgCCAQ/original
