### ISSUE TITLE
openai API 兼容问题及类型错误

### ISSUE THREAD

**Issue by lilonghe** [ant-design/x#247]
### 重现步骤

参照 https://x.ant.design/docs/react/model-use-qwen-cn 模型接入文档

### 类型错误
<img width="797" alt="截屏2024-11-26 16 44 01" src="https://github.com/user-attachments/assets/6cc82c7a-a9e1-43c7-946b-5cc9e3f8fdcb">

<img width="1119" alt="截屏2024-11-26 16 45 42" src="https://github.com/user-attachments/assets/7fc632f9-20e7-489e-835d-98b69063cf80">

### openai 兼容
直接调用上面示例文档中 agent.request 可以发出消息，但是得到的消息只能在 onUpdate 中拿到，无法配合 useXChat 使用  
使用配合 useXChat 的 onRequest 时，发送的消息格式就有问题

<img width="583" alt="截屏2024-11-26 16 48 23" src="https://github.com/user-attachments/assets/18964b8e-3ec0-4600-9826-1bddd5786eb2">

### 版本

1.0.0

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
感谢反馈，首先对于类型错误 `useXAgent` 支持传入范型参数，应该可以解决你的问题

```ts
import { useXAgent } from '@ant-design/x';

const [agent] = useXAgent<YourMessageType>(...);
```

**Comment by YumoImer** [comment]
> 直接调用上面示例文档中 agent.request 可以发出消息，但是得到的消息只能在 onUpdate 中拿到

对于这个问题，我没有能够复现。

**Comment by YumoImer** [comment]
> 使用配合 useXChat 的 onRequest 时，发送的消息格式就有问题

这里确定是一个 bug，我将对其进行修复，感谢反馈

**Comment by lilonghe** [comment]
> > 直接调用上面示例文档中 agent.request 可以发出消息，但是得到的消息只能在 onUpdate 中拿到
> 
> 对于这个问题，我没有能够复现。

不好意思，这里可能我说的不明确，重点其实是最后面的跟 useXChat 一起使用时，想着 agent 传给 useXChat 了，它调用也许也会更新 useXChat 的 message 数据

现在想来，这个应该是类似于一个独立的一次性请求函数，所以这条可以忽略
