### ISSUE TITLE
设计组件库需求

### ISSUE THREAD

**Issue by kidcvs** [ant-design/x#251]
### 需求动机

希望能尽早推出适用于Figma或MasterGo的设计组件库

**Comment by YumoImer** [comment]
好的，我会给设计师反馈。目前你可以在此处下载我们的 RICH sketch 设计资产。

![image](https://github.com/user-attachments/assets/ca7aa0c0-8c5d-4a55-a3a0-0384d249f406)

**Comment by YumoImer** [comment]
设计团队回复：暂时没有计划推出 Figma 或 MasterGo 资产
