### ISSUE TITLE
Ant Design X 官方文档演示页中“在Github上编辑此示例！”按钮触碰频闪

### ISSUE THREAD

**Issue by tabzzz1** [ant-design/x#254]
### 重现步骤

https://github.com/user-attachments/assets/8cf6222c-8f9c-4d7f-a07f-c18019eb6955

### 当前行为

如视频所示

### 预期行为

此按钮在hover状态下呈现正常样式

### 版本

1.0.0

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by tabzzz1** [comment]
并未在`/docs/playground/independent.tsx`下寻找到相关问题代码

**Comment by YumoImer** [comment]
感谢反馈，这确实是一个 bug，相关的代码在：.dumi/theme/builtins/Previewer/CodePreviewer.tsx

如果感兴趣的话可以帮我们修复下，非常感谢～ 😄

**Comment by tabzzz1** [comment]
@YumoImer 好！我将会完成它！
