### ISSUE TITLE
调用onUpdate会一直生成新的message

### ISSUE THREAD

**Issue by zazzzf** [ant-design/x#267]
### 重现步骤

```js
for await (const chunk of stream) {
      // 调用回调
      callbacks.onUpdate(chunk.choices[0]?.delta?.content || '');
    }
```

### 预期行为

为何会一直生成新的messge，是因为Id的问题吗，理解中onUpdate是会更新当前stream输出中的message

### 版本

1.0.0

**Comment by YumoImer** [comment]
代码上下文可以多写一点吗

**Comment by YumoImer** [comment]
这是示例文档的问题，已修复

**Comment by zazzzf** [comment]
> 这是示例文档的问题，已修复

是的 就是完全照抄的示例文档，走完这里后输出useChat内的messages会发现一只创建新的，id会是msg

**Comment by YumoImer** [comment]
好的，感谢反馈，今天会更新相关文档。

**Comment by yinjialu** [comment]
这个问题似乎是因为这一行导致的 @YumoImer 

let msg = getMessages().find((info) => info.id === updatingMsgId);

在 updateMessage 被反复触发时，通过 getMessages() 获取到 messages 列表始终没有更新，最新创建的 msg 匹配不到，然后一直创建新的 msg

https://github.com/ant-design/x/blob/ec243d73d94689c9bce5a7fc79c6a4f314b333f5/components/useXChat/index.ts#L166

**Comment by yinjialu** [comment]
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/8163172d-79c9-4b60-8d2a-b822c276e4d6">
打印了下日志，可以参考下

**Comment by YumoImer** [comment]
> 这个问题似乎是因为这一行导致的 @YumoImer
> 
> let msg = getMessages().find((info) => info.id === updatingMsgId);
> 
> 在 updateMessage 被反复触发时，通过 getMessages() 获取到 messages 列表始终没有更新，最新创建的 msg 匹配不到，然后一直创建新的 msg
> 
> https://github.com/ant-design/x/blob/ec243d73d94689c9bce5a7fc79c6a4f314b333f5/components/useXChat/index.ts#L166

是的，但这不是一个 BUG，设计如此。这个问题是文档中给的示例的问题。稍后我会更新。

**Comment by zazzzf** [comment]
> <img alt="image" width="1510" src="https://private-user-images.githubusercontent.com/37073056/390998115-8163172d-79c9-4b60-8d2a-b822c276e4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4Njc5NDgsIm5iZiI6MTczMjg2NzY0OCwicGF0aCI6Ii8zNzA3MzA1Ni8zOTA5OTgxMTUtODE2MzE3MmQtNzljOS00YjYwLThkMmEtYjgyMmMyNzZlNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDA4MDcyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMGUwNTAwNDYyODQwYzc4YTc5ODAwYjgxYjcxMmY1ZTk3YTVhYmRjMGRlOWNlMjg2ZjI3ZWM1MzkyMGJiNjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B5qJTeLdhArwnuTYAWYn3bGBM9vch8bmatVSMIowKiU"> 打印了下日志，可以参考下

是的我clone了项目调试了发现，首次update后没有find到msg，所以创建了一个新的msg，但是第二次stream解析后update进来，getMessages获得到的list并不包含刚刚创建的msg，所以会一直创建下去....

**Comment by zazzzf** [comment]
> > 这个问题似乎是因为这一行导致的 @YumoImer
> > let msg = getMessages().find((info) => info.id === updatingMsgId);
> > 在 updateMessage 被反复触发时，通过 getMessages() 获取到 messages 列表始终没有更新，最新创建的 msg 匹配不到，然后一直创建新的 msg
> > https://github.com/ant-design/x/blob/ec243d73d94689c9bce5a7fc79c6a4f314b333f5/components/useXChat/index.ts#L166
> 
> 是的，但这不是一个 BUG，设计如此。这个问题是文档中给的示例的问题。稍后我会更新。

貌似知道是什么原因了，openai的文档这里确实如果用await调用的话，会把所有的流await完之后一次性调用多次onUpdate导致出现了奇怪的问题，可能是openai这里update的方式有问题，可能有更好的调用方式

**Comment by zazzzf** [comment]
> > 这个问题似乎是因为这一行导致的 @YumoImer
> > let msg = getMessages().find((info) => info.id === updatingMsgId);
> > 在 updateMessage 被反复触发时，通过 getMessages() 获取到 messages 列表始终没有更新，最新创建的 msg 匹配不到，然后一直创建新的 msg
> > https://github.com/ant-design/x/blob/ec243d73d94689c9bce5a7fc79c6a4f314b333f5/components/useXChat/index.ts#L166
> 
> 是的，但这不是一个 BUG，设计如此。这个问题是文档中给的示例的问题。稍后我会更新。

似乎不是这里的问题，我观察了demo的代码，连续的onUpdate是没有问题的
https://github.com/ant-design/x/blob/ec243d73d94689c9bce5a7fc79c6a4f314b333f5/components/useXChat/demo/stream.tsx#L23-L32
但是在实际使用openai stream的循环中，调用的频率是高于demo的，会导致messages的更新出现问题，我改成这样后问题修复了，但是这并不是一个好的方案，可以参考一下
```js
const stream = await client.chat.completions.create({
    model: openaiModel,
    messages: [{ role: 'user', content: message }],
    stream: true,
  });

  let chunkstr = '';
  const update = throttle((chunk: any) => {
    onUpdate(chunk);
  }, 10);
  for await (const chunk of stream) {
    chunkstr += chunk.choices[0]?.delta?.content || '';
    if (chunk.choices[0]?.finish_reason === 'stop') {
      onSuccess(chunkstr);
      break;
    }
    update(chunkstr);
  }
```

**Comment by yinjialu** [comment]
这个是更新了哪个文档呢？

**Comment by yinjialu** [comment]
@YumoImer hello，看了下diff信息，核心是从

callbacks.onUpdate(chunk.choices[0]?.delta?.content || '');

调整为了 

content += chunk.choices[0]?.delta?.content || '';

只是确保 update 的时候的信息是完整的，这个看着还不能解决持续创建新的 msg 的问题，也就是我上面截图反馈的现象，过程中创建了多个重复递进的 msg，而不是流式渲染

**Comment by YumoImer** [comment]
> @YumoImer hello，看了下diff信息，核心是从
> 
> callbacks.onUpdate(chunk.choices[0]?.delta?.content || '');
> 
> 调整为了
> 
> content += chunk.choices[0]?.delta?.content || '';
> 
> 只是确保 update 的时候的信息是完整的，这个看着还不能解决持续创建新的 msg 的问题，也就是我上面截图反馈的现象，过程中创建了多个重复递进的 msg，而不是流式渲染

目前已经解决了这个问题，本质上是之前文档中代码示例的问题，现在添加消息的 key 后就不存在这个问题了，可以[对着更新后的文档试试](https://x.ant.design/docs/react/model-use-qwen-cn)。

![image](https://github.com/user-attachments/assets/705f9ba1-a114-497c-a0c7-8a33053a1e32)

**Comment by YumoImer** [comment]
> > @YumoImer hello，看了下diff信息，核心是从
> 
> > 
> 
> > callbacks.onUpdate(chunk.choices[0]?.delta?.content || '');
> 
> > 
> 
> > 调整为了
> 
> > 
> 
> > content += chunk.choices[0]?.delta?.content || '';
> 
> > 
> 
> > 只是确保 update 的时候的信息是完整的，这个看着还不能解决持续创建新的 msg 的问题，也就是我上面截图反馈的现象，过程中创建了多个重复递进的 msg，而不是流式渲染
> 
> 
> 
> +1 仍然有问题。。。

贴一段完整的代码看看

**Comment by YumoImer** [comment]
使用文档示例代码：
https://x.ant.design/docs/react/model-use-qwen-cn#%E4%BD%BF%E7%94%A8-api-%E6%8E%A5%E5%85%A5

效果：

https://github.com/user-attachments/assets/8b2c3e90-0809-479d-afce-2a06d9536790

**Comment by yinjialu** [comment]
我的解决办法可以参考下：

import { flushSync } from 'react-dom';
flushSync(() => {
    onUpdate(currentAnswer);
});

使用 flushSync 确保每次更新立即执行 render

建议这里的更新 messages 的逻辑可以整体调整为 setMessages((ori) => {
      // 在内部进行 updatingMsgId 的匹配判断
}) 
https://github.com/ant-design/x/blob/a12d76eaf2b5d1c4cab09efd7a2ff241f4834b44/components/useXChat/index.ts#L165

**Comment by YumoImer** [comment]
抱歉，由于这是一个偶发问题，之前我在本地一直没能触发，昨天已经确认是有问题的。这块我正在修复。

https://github.com/ant-design/x/issues/294
