### ISSUE TITLE
XRequest 能否支持 ollama 返回的 application/x-ndjson 内容

### ISSUE THREAD

**Issue by wolfwood1983** [ant-design/x#284]
### 需求动机

XRequest能否支持ollama的response，需要header中的content-type支持application/x-ndjson
![2024-11-30_1-31-45](https://github.com/user-attachments/assets/948ed64f-0edf-49ba-b211-e8f3185eac87)
![2024-11-30_1-32-21](https://github.com/user-attachments/assets/6614543e-f180-4cc8-b7ba-55d09f9a6a5a)

**Comment by YumoImer** [comment]
感谢反馈，这是个bug，我来处理下
