### ISSUE TITLE
Bubble 组件的 typing 属性支持用户自定义打字机效果后缀

### ISSUE THREAD

**Issue by YumoImer** [ant-design/x#289]
### 需求动机

![image](https://github.com/user-attachments/assets/1ea99547-3e40-4d8f-88e7-3e3634b37fcb)

### 提议的 API 是什么样的？

```ts
export interface TypingOption {
  step?: number;
  interval?: number;
  /** + New Option ⬇️ */
  suffix?: React.ReactNode;
}
```

**Comment by BQXBQX** [comment]
Thank you for reviewing 🥺
https://github.com/ant-design/x/pull/312
