### ISSUE TITLE
useXChat消息合并异常

### ISSUE THREAD

**Issue by JacobZyy** [ant-design/x#294]
### 重现步骤

在线示例链接：（必填）（）
https://stackblitz.com/edit/stackblitz-starters-9ejyvz?description=The%20React%20framework%20for%20production&file=app%2FTest.tsx,app%2Fpage.tsx,package.json&title=Next.js%20Starter

<img width="405" alt="image" src="https://github.com/user-attachments/assets/1edb0a75-b127-468c-a1f8-2e30e80a39a4">

### 当前行为

消息合并异常，看了下源码
useXChat 下  updateMessage方法里`let msg = getMessages().find((info) => info.id === updatingMsgId);`的`useSyncState`返回的`getMessage()`里，返回的是useLatest的message这个state。
```tsx
  const stateRef = React.useRef(state);
  stateRef.current = state;

  const getState = React.useCallback(() => stateRef.current, []);
```
取到的还是一个快照而非fiber上的最新值
```tsx
   const updateMessage = (message: AgentMessage, status: MessageStatus) => {
      let msg = getMessages().find((info) => info.id === updatingMsgId);
      console.log('updateMessage', msg, updatingMsgId);
      if (!msg) {
      // Create if not exist
        msg = createMessage(message, status);
        setMessages((ori) => {
          const oriWithoutPending = ori.filter((info) => info.id !== loadingMsgId);
          return [...oriWithoutPending, msg!];
        });
        updatingMsgId = msg.id;
      } 
```
<img width="278" alt="image" src="https://github.com/user-attachments/assets/7630d15d-15dd-4af6-9f30-2f1227b137f7">
导致一直创建新的message。

### 版本

1.0.1

**Comment by YumoImer** [comment]
我本地无法复现，用你的在线链接是可以复现的，我来确认下问题。感谢！

**Comment by YumoImer** [comment]
非常感谢！可能是偶然，之前一直没能复现，刚复现了，这是一个偶发性 bug ，我会尽快修复。

![image](https://github.com/user-attachments/assets/209e17d8-bd2a-4720-b522-ece0b42f0890)

**Comment by YumoImer** [comment]
@JacobZyy 对了，请及时销毁你的 API_KEY，重新创建

**Comment by JacobZyy** [comment]
> @JacobZyy 对了，请及时销毁你的 API_KEY，重新创建

问题不大。加了限额+过期时间哈哈哈。感谢感谢

**Comment by zazzzf** [comment]
千问的API不会有问题，openai相关的才会这样～，代码是一样的

**Comment by zazzzf** [comment]
> 千问的API不会有问题，openai相关的才会这样～，代码是一样的

好像是openai的响应太快了～

**Comment by YumoImer** [comment]
> 千问的API不会有问题，openai相关的才会这样～，代码是一样的

不是的，和模型无关。多试几次就会复现。我正在修。原因上面已经描述了。

**Comment by katoto** [comment]
<img width="668" alt="image" src="https://github.com/user-attachments/assets/65dbd876-8696-4f64-85f0-5b2b8346db8b">
+1
