### ISSUE TITLE
Ant Design X 会话设计介绍页内容链接 404

### ISSUE THREAD

**Issue by TimSamaMo** [ant-design/x#297]
### Reproduction link

[https://x.ant.design/docs/spec/conversation-design-cn#%E5%AF%B9%E8%AF%9D%E7%BB%84%E4%BB%B6%E9%A2%84%E8%A7%88](https://x.ant.design/docs/spec/conversation-design-cn#%E5%AF%B9%E8%AF%9D%E7%BB%84%E4%BB%B6%E9%A2%84%E8%A7%88)

### Steps to reproduce

这里的链接，应该链到 Ant Design X 中，不应该去语雀吧。

### What is expected?

同上。

### What is actually happening?

404

| Environment | Info |
| --- | --- |
| antd | undefined |
| React | - |
| System | - |
| Browser | - |

**Comment by YumoImer** [comment]
这是一类问题，需要后续处理下。

**Comment by TimSamaMo** [comment]
能不能给个 Sketch 组件库文件，现在下载不了。。

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/pull/334

**Comment by afc163** [comment]
在 PR 里用关键字关联即可自动关闭：https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue

**Comment by YumoImer** [comment]
> 在 PR 里用关键字关联即可自动关闭：https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue @YumoImer 

忘记 link 了，过 issues 的时候才想起来。。
