### ISSUE TITLE
组件库 Sketch 文件的链接 404，能不能发一下 Sketch 文件啊。。

### ISSUE THREAD

**Issue by TimSamaMo** [ant-design/x#300]
https://x.ant.design/docs/spec/hybrid-ui-design-cn#how%E8%B5%84%E4%BA%A7%E4%BD%BF%E7%94%A8
这里的链接无法下载，能不能给个文件啊，谢谢。

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/discussions/256

可以在这里获取

**Comment by YumoImer** [comment]
后续需要将文档中的链接替换

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/pull/334
