### ISSUE TITLE
useXChat 用setMessages 设置历史聊天数据, 再次聊天 messages 返回的消息列表 id 重复

### ISSUE THREAD

**Issue by katoto** [ant-design/x#309]
### 重现步骤

在线示例链接：https://codesandbox.io/p/sandbox/x6vg6t

步骤：
1. 打开sandbox 替换个能用的 apiKey
2. 点击 “设置默认消息” 按钮 
3. 开始继续聊天, 会返回一样ID , id 没有和历史消息累加

<img width="1208" alt="image" src="https://github.com/user-attachments/assets/bc0c7c6d-03d2-4d48-9a9f-adb49220bb4f">

![image](https://github.com/user-attachments/assets/2449a7b7-7db2-47ce-85b6-1d79f66cbcce)

用 defaultMessages 也会有这个现象

### 当前行为

id 重复 

### 预期行为

id 不重复。历史消息数据下生成新id .

### 版本

1.0.2

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
这不是 bug，这里需要自行保证消息去重。因为 useXChat 对消息体的内容定义是一个范型，所以不会去识别 ID 去重。

![image](https://github.com/user-attachments/assets/690ed20a-ddfc-418b-8c32-73e916688fcb)

**Comment by katoto** [comment]
好滴 tk

**Comment by changmen1** [comment]
> 这不是 bug，这里需要自行保证消息去重。因为 useXChat 对消息体的内容定义是一个范型，所以不会去识别 ID 去重。
> 
> ![image](https://github.com/user-attachments/assets/690ed20a-ddfc-418b-8c32-73e916688fcb)

我也遇到了相同的问题 如果按照你说的去重的话 不是会丢失历史数据吗

**Comment by notFoundTheGuy** [comment]
+1

**Comment by 3026546679** [comment]
所以应该怎么解决呢，如何正确的设置历史记录，因为    defaultMessages 没有接收id，所以会默认从新开始
