### ISSUE TITLE
这个应该不支持ant design 4版本吧

### ISSUE THREAD

**Issue by zengxpang** [ant-design/x#310]
### 重现步骤

在线示例链接：（必填）

步骤：
1.
2.
3.

### 版本

1

**Comment by YumoImer** [comment]
感谢反馈，这不是 bug 哈。目前 X 基于 V5 版本开发，升级 antd 参考这里：

https://ant.design/docs/react/migration-v5-cn?theme=dark

**Comment by zombieJ** [comment]
是的，不支持。v4 已经过维护期很多年了，也不会基于它做支持了哈。
