### ISSUE TITLE
低版本antd使用报错

### ISSUE THREAD

**Issue by shenqistart** [ant-design/x#311]
### 重现步骤

在线示例链接：（必填）

步骤：
1.  "antd": "^4.24.16"
2.  引入Sender组件
3. 有如下报错，查询底层依赖的是5版本的，但因为是老项目升级不了antd版本
![image](https://github.com/user-attachments/assets/710b4882-af43-4a2d-b0b0-f92162b65d65)

### 当前行为

底层包版本兼容问题

### 预期行为

没有报错

### 版本

1.0.2

**Comment by zombieJ** [comment]
v4 已经过了维护期多年了哈~

https://github.com/ant-design/x/issues/310#issuecomment-2519770387
