### ISSUE TITLE
Bubble.list的 autoScroll属性不生效

### ISSUE THREAD

**Issue by kkifx** [ant-design/x#317]
### 重现步骤

在线示例链接：（必填）

步骤：
1.
2.
3.

### 当前行为

Bubble.list的 autoScroll属性不生效

### 预期行为

Bubble.list的 autoScroll属性 当内容更新时，自动滚动到最新位置。如果用户滚动，则会暂停自动滚动。

### 版本

1.0.1

**Comment by YumoImer** [comment]
最小的复现仓库可以提供下，感谢！

**Comment by kkifx** [comment]
https://github.com/user-attachments/assets/49f83689-8887-40df-9b1f-4a46fd977478

现象如上，使用的代码就是独立式样板间的代码，只增加了bubble.list的autoscroll属性为true,但是不生效，
![image](https://github.com/user-attachments/assets/0197bbf3-ab4c-4cc5-9c81-2713666458e7)

**Comment by kkifx** [comment]
样板间代码地址-https://github.com/ant-design/x/blob/main/docs/playground/independent.tsx

**Comment by anzhou99** [comment]
@YumoImer 针对这个提了PR，还请审阅一下 https://github.com/ant-design/x/pull/327

**Comment by YumoImer** [comment]
这不是个 bug，设计如此。上述现象只有在用户操作了滚轮后且最后一条消息不可见时才会出现。[官网有描述](https://x.ant.design/components/bubble-cn#bubblelist)。

这样设计的原因：「每次消息列表的更新都触发滚动至底部」这不是一个通用逻辑，所以我们暴露了 Ref 支持用户自己控制。

@kkifx 看下是否解决你的疑问，另外 @anzhou99 感谢你的积极参与！

**Comment by anzhou99** [comment]
> 设计如此。上述现象只有在用户操作了滚轮后且

我理解预期的行为应该是：
1.  用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；
2.  用户执行手动滚动操作后，父容器不执行自动滚动逻辑；
3.  用户重新滚动到父容器最底部后，父容器重新开始执行自动滚动到最底部的逻辑。

以上逻辑也和ChatGPT的逻辑相似，看看咱们的理解一致么 @YumoImer @kkifx 

如果是的话，目前的组件应该是没法很好的完成第一步这个逻辑的（还是说和浏览器有关，我这边显示不正常）。

**Comment by LofiSu** [comment]
> 这不是个 bug，设计如此。上述现象只有在用户操作了滚轮后且最后一条消息不可见时才会出现。[官网有描述](https://x.ant.design/components/bubble-cn#bubblelist)。
> 
> 这样设计的原因：「每次消息列表的更新都触发滚动至底部」这不是一个通用逻辑，所以我们暴露了 Ref 支持用户自己控制。
> 
> @kkifx 看下是否解决你的疑问，另外 @anzhou99 感谢你的积极参与！

自动滚动（autoScroll）：

当新内容（如消息）添加时，BubbleList 需要自动滚动到列表底部。如果用户手动滚动到顶部或者中间，自动滚动应该被暂停。
onInternalScroll 用来检测用户是否手动滚动过，如果滚动到顶部，则暂停自动滚动。
滚动检测和处理：

自动滚动的判断依赖于 scrollReachEnd 状态，这个状态标志着当前是否已经滚动到底部。
每当 displayData 或者 updateCount 更新时，useEffect 会尝试自动滚动到底部。
manualScrollToBottom 方法：

通过外部调用该方法，开发者可以手动触发滚动到底部的行为，适用于程序化滚动。

**Comment by YumoImer** [comment]
> 1. 用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；

这个场景需要明确下，什么情况算「用户无操作」，以及现在的实现是否满足不了 or 存在 bug。

对于 2、3 我和你的观点一致，也符合该组件的预期

**Comment by anzhou99** [comment]
> > 1. 用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；
> 
> 这个场景需要明确下，什么情况算「用户无操作」，以及现在的实现是否满足不了 or 存在 bug。
> 
> 对于 2、3 我和你的观点一致，也符合该组件的预期

用户无操作 确实表述不够明确，意思具体是指消息容器组件初始化后，用户没有手动进行过滚动操作

**Comment by kkifx** [comment]
> > 设计如此。上述现象只有在用户操作了滚轮后且
> 
> 我理解预期的行为应该是：
> 
> 1. 用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；
> 2. 用户执行手动滚动操作后，父容器不执行自动滚动逻辑；
> 3. 用户重新滚动到父容器最底部后，父容器重新开始执行自动滚动到最底部的逻辑。
> 
> 以上逻辑也和ChatGPT的逻辑相似，看看咱们的理解一致么 @YumoImer @kkifx
> 
> 如果是的话，目前的组件应该是没法很好的完成第一步这个逻辑的（还是说和浏览器有关，我这边显示不正常）。

我同意这样的组件行为，现在组件存在问题是我点击消息发送后，滚动条会先滚动到底部，在内容生成的过程中，只有第一行到第二行，滚动条会同步触底，到第三行，滚动条就没有更新了，不知你们是否有这个问题 @anzhou99 @YumoImer

**Comment by kkifx** [comment]
> 这不是个 bug，设计如此。上述现象只有在用户操作了滚轮后且最后一条消息不可见时才会出现。[官网有描述](https://x.ant.design/components/bubble-cn#bubblelist)。
> 
> 这样设计的原因：「每次消息列表的更新都触发滚动至底部」这不是一个通用逻辑，所以我们暴露了 Ref 支持用户自己控制。
> 
> @kkifx 看下是否解决你的疑问，另外 @anzhou99 感谢你的积极参与！
您好，用户不操作滚轮，消息的更新也有问题，我点击消息发送后，滚动条会先滚动到底部，在内容生成的过程中，只有第一行到第二行，滚动条会同步触底，到第三行，滚动条就没有更新了

**Comment by anzhou99** [comment]
> 
> 我同意这样的组件行为，现在组件存在问题是我点击消息发送后，滚动条会先滚动到底部，在内容生成的过程中，只有第一行到第二行，滚动条会同步触底，到第三行，滚动条就没有更新了，不知你们是否有这个问题 @anzhou99 @YumoImer

我这边确实也存在你所说的问题

**Comment by YumoImer** [comment]
> 1.用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；

> 用户无操作 确实表述不够明确，意思具体是指消息容器组件初始化后，用户没有手动进行过滚动操作

#### 环境

Version：1.0.2
UA：'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'

#### 验证

对于 Case 1 这里是验证视频, 我没有进行任何对滚轮的操作：

Uploading 录屏2024-12-11 02.07.50.mov…

**Comment by anzhou99** [comment]
> > 1.用户无操作时，消息父容器应始终可以自动滚动到最底部，使得最新消息能够始终显示完整；
> 
> > 用户无操作 确实表述不够明确，意思具体是指消息容器组件初始化后，用户没有手动进行过滚动操作
> 
> #### 环境
> Version：1.0.2 UA：'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36'
> 
> #### 验证
> 对于 Case 1 这里是验证录屏, 过程中我没有对滚轮进行任何的操作，看起来是没有问题的。

问题还是在于[`scrollTop`可能会是一个小数](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollTop)， 这会导致BubbleList.tsx中的判断是否达到底部的逻辑无法按预期执行：
>
```
  const onInternalScroll: React.UIEventHandler<HTMLDivElement> = (e) => {
    const target = e.target as HTMLElement;

    setScrollReachEnd(target.scrollTop + target.clientHeight === target.scrollHeight);
  };
```
正是因为`scrollTop`在不同的屏幕表现不一致，所以出现了你这边无法复现问题的情况。
这边我针对加了误差，重新提了PR https://github.com/ant-design/x/pull/336。请看一下吧 @YumoImer

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/pull/336

**Comment by hgchenhao** [comment]
> > 这不是个 bug，设计如此。上述现象只有在用户操作了滚轮后且最后一条消息不可见时才会出现。[官网有描述](https://x.ant.design/components/bubble-cn#bubblelist)。
> > 这样设计的原因：「每次消息列表的更新都触发滚动至底部」这不是一个通用逻辑，所以我们暴露了 Ref 支持用户自己控制。
> > [@kkifx](https://github.com/kkifx) 看下是否解决你的疑问，另外 [@anzhou99](https://github.com/anzhou99) 感谢你的积极参与！
> > 您好，用户不操作滚轮，消息的更新也有问题，我点击消息发送后，滚动条会先滚动到底部，在内容生成的过程中，只有第一行到第二行，滚动条会同步触底，到第三行，滚动条就没有更新了

我也是到第三行，滚动条就没有更新了，请问解决了吗

**Comment by hgchenhao** [comment]
> [#336](https://github.com/ant-design/x/pull/336)

这个TOLERANCE 配置能支持自定义吗
