### ISSUE TITLE
Bubble内容区增加header后，样式错误

### ISSUE THREAD

**Issue by GHTlinyu** [ant-design/x#318]
### 重现步骤

在线示例链接：（必填）

https://stackblitz.com/edit/react-nda6bo?file=demo.tsx

步骤：
1.  Bubble组件，placement="end"
2. header增加内容

![image](https://github.com/user-attachments/assets/f320575c-331e-4250-9d06-2e5f84150ebb)

### 当前行为

内容块显示在左侧

### 预期行为

内容块显示在右侧，挨着头像

### 版本

1.0.2

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
这确实是个 bug，我来处理

**Comment by tabzzz1** [comment]
> 这确实是个 bug，我来处理

您进展如何？我在处理 #296 时遇到了同样的问题，问题貌似出在`./style/index.ts`中的93行部分，我通过删除`alignItems: flex-start`和`flex: auto`解决了这个问题，同时在`header`中通过将内容放在`Flex`布局中并添加`justify="end"`实现了此issue的“样式”问题。方便分享下您的解决思路吗？

**Comment by YumoImer** [comment]
@tabzzz1 感谢！昨天太晚休息了，今天我来看下。问题确实出在 content-wrapper ，同时我这边在处理内容溢出的问题也和这里有关，我来综合考虑修复
