### ISSUE TITLE
Does not work with Next.js Pages Router

### ISSUE THREAD

**Issue by nvzoll** [ant-design/x#320]
### 重现步骤

在线示例链接：（必填）
https://codesandbox.io/p/devbox/busy-ace-j893yp

步骤：
1. npx create-next-app@14.2.20 antdx-demo-pages
2. Use App Router - No
3. cd antdx-demo-pages
4. npm install @ant-design/x --save
5. pages/index.tsx, paste snippet from example https://x.ant.design/docs/react/use-with-next#importing-ant-designx
6. npm run dev

### 当前行为

SyntaxError: Cannot use import statement outside a module

### 预期行为

Page renders

### 上下文

Use ant-design/x with Next.JS web app which uses Pages Router

### 版本

1.0.2

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
https://github.com/vercel/next.js/pull/58992

**Comment by YumoImer** [comment]
This is an issue related to Next.js.

**Comment by tang9527** [comment]
> Additional note: attempt to transpile antd and related packages with next.config.js brings following error
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'defaultAlgorithm')
>     at eval (webpack-internal:///./node_modules/@ant-design/x/lib/theme/useToken.js:25:60)
>     at ./node_modules/@ant-design/x/lib/theme/useToken.js (J:\work\app\.next\server\vendor-chunks\@ant-design.js:19688:1)
>     at __webpack_require__ (J:\work\app\.next\server\webpack-runtime.js:33:43)
>     at eval (webpack-internal:///./node_modules/@ant-design/x/lib/theme/genStyleUtils.js:9:17)
>     at ./node_modules/@ant-design/x/lib/theme/genStyleUtils.js (J:\work\app\.next\server\vendor-chunks\@ant-design.js:19677:1)
>     at __webpack_require__ (J:\work\app\.next\server\webpack-runtime.js:33:43)
>     at eval (webpack-internal:///./node_modules/@ant-design/x/lib/attachments/style/index.js:15:22)
>     at ./node_modules/@ant-design/x/lib/attachments/style/index.js (J:\work\app\.next\server\vendor-chunks\@ant-design.js:19270:1)
>     at __webpack_require__ (J:\work\app\.next\server\webpack-runtime.js:33:43)
>     at eval (webpack-internal:///./node_modules/@ant-design/x/lib/attachments/FileList/FileListCard.js:13:37)
>     at ./node_modules/@ant-design/x/lib/attachments/FileList/FileListCard.js (J:\work\app\.next\server\vendor-chunks\@ant-design.js:19171:1)
>     at __webpack_require__ (J:\work\app\.next\server\webpack-runtime.js:33:43)
>     at eval (webpack-internal:///./node_modules/@ant-design/x/lib/attachments/FileList/index.js:20:44)
>     at ./node_modules/@ant-design/x/lib/attachments/FileList/index.js (J:\work\app\.next\server\vendor-chunks\@ant-design.js:19204:1)
>     at __webpack_require__ (J:\work\app\.next\server\webpack-runtime.js:33:43) {
>     ```
> ```

Make sure the antd version in the project is consistent with this one

https://github.com/ant-design/x/blob/main/package.json#L161C15-L161C21
