### ISSUE TITLE
后续会提供一个类似prochat一样的大模版组件吗，基于其他原子组件和hooks实现

### ISSUE THREAD

**Issue by lch000** [ant-design/x#322]
### 需求动机

对于一般场景下的chat，是否考虑出一个模版组件xChat，由sender，bubble.List，useXagent和useXchat等其他原子组件组成，内置消息重发，暂停发送等功能？

**Comment by YumoImer** [comment]
后续会提供更多的基础样板间。

但暂时没有计划将其封装为一个 Chat 组件，因为可定制的地方实在太多，所以提供一些基础样板间仅供开发者参考可能更实际点。

已在计划中的基础样板间：
![image](https://github.com/user-attachments/assets/daef2aab-379c-4dd3-bb24-8eb36ed8292d)

**Comment by YumoImer** [comment]
如没有其他问题，请自行 close 哈，感谢。 @lch000
