### ISSUE TITLE
【BUG】构建错误，用pnpm和cnpm构建的时候报错ReferenceError: mapboxgl is not defined

### ISSUE THREAD

**Issue by LofiSu** [ant-design/x#330]
### 重现步骤

用pnpm i和cnpm i之后点击Bubble
对话气泡或者其他的页面就会报错
![image](https://github.com/user-attachments/assets/9923b875-8ffe-420e-9496-45573bb4efe7)

### 当前行为

把这两行注释掉就可以用了
![image](https://github.com/user-attachments/assets/b3bbb293-64d9-40c3-a957-62c3a8f12bd0)
但是Umi构建速度特别慢，三分钟才能构建好，感觉没有热更新

### 版本

lastest

**Comment by LofiSu** [comment]
![image](https://github.com/user-attachments/assets/e2167dcf-ba0b-4532-b4b2-dd0ea19c731a)
每次这个要构建特别久，要三分钟，改一点代码就要重新构建

**Comment by LofiSu** [comment]
![image](https://github.com/user-attachments/assets/d2956ee7-158f-4c2f-906c-b97e18d721b9)
![image](https://github.com/user-attachments/assets/e067389e-2061-446c-9739-4ff1686c3c74)
这个确实是跟官网不一样吗

**Comment by YumoImer** [comment]
> ![image](https://private-user-images.githubusercontent.com/163713803/393758769-d2956ee7-158f-4c2f-906c-b97e18d721b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NTE3NDUsIm5iZiI6MTczMzg1MTQ0NSwicGF0aCI6Ii8xNjM3MTM4MDMvMzkzNzU4NzY5LWQyOTU2ZWU3LTE1OGYtNGMyZi05MDZjLWI5N2UxOGQ3MjFiOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNzI0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMWExOGRmNWNiYTI5OTI1N2ViYzZiZTQ5ZDkyZTRmODJkZjAwZWIxZGMwZDBjY2YyMDc1Nzg5YWE5OThiODU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JouFpCJGhMZbIfmb8NYPWy2a01jBSlcki3Mf_-hDbDs) ![image](https://private-user-images.githubusercontent.com/163713803/393758823-e067389e-2061-446c-9739-4ff1686c3c74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NTE3NDUsIm5iZiI6MTczMzg1MTQ0NSwicGF0aCI6Ii8xNjM3MTM4MDMvMzkzNzU4ODIzLWUwNjczODllLTIwNjEtNDQ2Yy05NzM5LTRmZjE2ODZjM2M3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQxNzI0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MjkxYzE2Mzk1MmY1NWNlN2E2NzQ2M2VjZmRiMTJkMjAxZDE0ZTg4ZjAyY2ZhYjczM2NhMjZmZjA1ZmNhMDk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.jOb7JhF1wxBFMMbiJo6FOzBI-slKgoe3IZ20TYbdeak) 这个确实是跟官网不一样吗

Debug Only。

![image](https://github.com/user-attachments/assets/f3318283-3c35-467c-b242-70ae4831558d)
