### ISSUE TITLE
useXAgent中自定义请求如何获取完整的聊天记录

### ISSUE THREAD

**Issue by whi-sper** [ant-design/x#335]
### 重现步骤

伪代码如下：
const {chatMessages} = useStore();
console.log(chatMessages) // 这里值正常
const [agent] = useXAgent({
    request: async ({ message }, { onSuccess }) => {
      setStreamLoading(true);
      // @这里值有缓存
      console.log('onRequest: ', message, toJS(chatMessages));
     request(
        `${CHAT_PATH}`,
        {
          messages: chatMessages
        }
      );
    }
  });

### 当前行为

自定义请求中拿不到真实的chatMessages,只要聊过的信息都存在其中了

### 预期行为

拿到这次的聊天记录

### 上下文

一个聊天机器人。在清空记录的按钮处清空了store中的chatMessages值，在useXAgent中拿不到真实的值

### 版本

1.0.2

### 您在哪些浏览器上遇到了这个问题？

Chrome

**Comment by YumoImer** [comment]
感觉是这里的问题 `const {chatMessages} = useStore();`

另外，提供下最小复现示例。

**Comment by whi-sper** [comment]
> 感觉是这里的问题 `const {chatMessages} = useStore();`
> 
> 另外，提供下最小复现示例。

你好，感谢及时的反馈
我fork官方示例，并增加了一个count状态值，以下是在线示例
https://stackblitz.com/edit/react-vrsj8r2f?file=demo.tsx
"----count"打印值一直为0
看起来是个闭包问题；但是否意味着在useXAgent中用到的状态值都需要使用ref来获取最新值吗？

**Comment by YumoImer** [comment]
> > 感觉是这里的问题 `const {chatMessages} = useStore();`
> > 另外，提供下最小复现示例。
> 
> 你好，感谢及时的反馈 我fork官方示例，并增加了一个count状态值，以下是在线示例 https://stackblitz.com/edit/react-vrsj8r2f?file=demo.tsx "----count"打印值一直为0 看起来是个闭包问题；但是否意味着在useXAgent中用到的状态值都需要使用ref来获取最新值吗？

我梳理了一下，这和闭包应该没有关系:
 - `useXAgent` 的 `request` 里拿到的 `message` 是当前的用户消息，且还没有触发网络请求，所以你的 chatMessages 不会更新。
 - 我认为如果使用你代码中的 useStore 管理状态，那么其实 `useXChat` 最好不要使用，不然会有两个地方对数据流进行处理。

**Comment by YumoImer** [comment]
如果使用 `useXChat` 那你可以这样获取完整的消息列表数据：

``` tsx
const { messages } = useXChat({ agent });
```

**Comment by whi-sper** [comment]
> 如果使用 `useXChat` 那你可以这样获取完整的消息列表数据：
> 
> ```tsx
> const { messages } = useXChat({ agent });
> ```
感谢回复
1、我的自定义请求是需要传完整messages列表的，所以我的需求是在useXAgent的request中拿到全部messages列表；useXChat中获取满足不了
2、我理解这是一个闭包问题，request函数被定义的时候捕获了当时的count值，即使后续的更新，request也不会再更新，如果是这个问题，是否考虑在useXAgent中增加依赖的传参呢？

**Comment by YumoImer** [comment]
> > 如果使用 `useXChat` 那你可以这样获取完整的消息列表数据：
> > ```tsx
> > const { messages } = useXChat({ agent });
> > ```
> 
> 感谢回复 1、我的自定义请求是需要传完整messages列表的，所以我的需求是在useXAgent的request中拿到全部messages列表；useXChat中获取满足不了 2、我理解这是一个闭包问题，request函数被定义的时候捕获了当时的count值，即使后续的更新，request也不会再更新，如果是这个问题，是否考虑在useXAgent中增加依赖的传参呢？

---

明白了，对于问题1:
可以使用 `useXAgent` 配合 `useXChat` 来使用， `info.messages` 为全部的消息列表 `info.message` 为当前消息，整体的代码在[文档](https://x.ant.design/docs/react/model-use-qwen-cn)中：
![image](https://github.com/user-attachments/assets/f00316ec-0b07-4df6-9dfa-de4e7889091b)

---

对于问题2:
抱歉，我理解有问题，确实是这样的， `useXAgent` 的定位是对接模型推理服务，所以不会去做状态管理，那「增加依赖的传参」也不会考虑，怎么配合做状态管理，可以参考 `useXChat`  的实现～

**Comment by fuyunzhishang** [comment]
这就很奇怪啊，useXChat返回的request不能获取最新状态，调用模型的时候也不可能只传递默认参数，不然还要fork源码自定义组件？

**Comment by OnceCrazyer** [comment]
> 这就很奇怪啊，useXChat返回的request不能获取最新状态，调用模型的时候也不可能只传递默认参数，不然还要fork源码自定义组件？

我也遇到这个问题，想传额外参数发现不支持，想获取全局参数获取不到

**Comment by 94dreamer** [comment]
的确是

**Comment by 94dreamer** [comment]
这个问题就close了？
