### ISSUE TITLE
Sender onChange 访问事件对象能力扩展

### ISSUE THREAD

**Issue by defaultjacky** [ant-design/x#338]
### 需求动机

目前 Sender onChange 只能访问到输入框对应 string value
onChange?: (value: string) => void
期望可以访问完整的事件对象

### 提议的 API 是什么样的？

onChangeEvent?: (e:React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>
) => void;

**Comment by LofiSu** [comment]
> 目前 Sender onChange 只能访问到输入框对应 string value
> onChange?: (value: string) => void
> 期望可以访问完整的事件对象

interface SenderProps {
  value?: string;
  onChange?: (event: React.ChangeEvent<HTMLInputElement>) => void; // 接收完整事件
  // 其他 props
}
这个我可以去改一下hh

**Comment by defaultjacky** [comment]
PR @YumoImer
