### ISSUE TITLE
按useXChat演示代码，使用流式输出更新内容无效，还是一次性输出

### ISSUE THREAD

**Issue by 59050498** [ant-design/x#339]
### 重现步骤

const [agent] = useXAgent({
    request: async ({ message }, { onSuccess, onUpdate }) => {
      const fullContent = `Streaming output instead of Bubble typing effect. You typed: ${message}`;
      let currentContent = '';

      const id = setInterval(() => {
        currentContent = fullContent.slice(0, currentContent.length + 2);
        onUpdate(currentContent);

        if (currentContent === fullContent) {
          clearInterval(id);
          onSuccess(fullContent);
        }
      }, 100);
    },
  });

  // Chat messages
  const { onRequest, messages } = useXChat({
    agent,
  });

开发环境 antd pro 6.0，ant-design x 1.0.2

### 版本

1.0.2

### 您在哪些浏览器上遇到了这个问题？

Chrome, Microsoft Edge

**Comment by JakimLi** [comment]
这个为什么closed了？怎么解决呢？
