### ISSUE TITLE
antdX能不能，不基于antd5呢？

### ISSUE THREAD

**Issue by DayBreakJS** [ant-design/x#341]
### 需求动机

项目是antd4的版本，由于antd5 css-in-js的方案，升级成本较高，但想用antdx，无法兼容4，在开发中带来了极大的难题。
在安装时，是否 可以选择基于antd4还是antd5？

**Comment by zombieJ** [comment]
v4 已经过了维护期多年了哈~

https://github.com/ant-design/x/issues/310#issuecomment-2519770387
