### ISSUE TITLE
Raise Error Use XProvider

### ISSUE THREAD

**Issue by hamedyosefian** [ant-design/x#355]
### 重现步骤

在线示例链接：（必填）

步骤：
1. Open _app.tsx
2. Add import { XProvider } from '@ant-design/x';
3. Raise an error "Cannot use import statement outside a module"

### 当前行为

when use  import { XProvider } from '@ant-design/x' before use that raise errror in project "Cannot use import statement outside a module"

### 版本

1.0.2

**Comment by YumoImer** [comment]
This is an issue related to Next.js. https://github.com/vercel/next.js/pull/58992

And its already exists. https://github.com/ant-design/x/issues/320
