### ISSUE TITLE
Not work placement with header and footer

### ISSUE THREAD

**Issue by hamedyosefian** [ant-design/x#356]
### 重现步骤

在线示例链接：（必填）

步骤：
1.add bubbles component with props placement and content that worked
2.when add footer or header to each bubble component that change placement to start

### 版本

1.0.2

**Comment by zxsa89675** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the Bubble component to ensure that the placement prop works correctly even when header or footer is added. The fix involves updating the className logic for the main wrapper div to include the placement class regardless of whether header or footer is present.

You can review changes in this commit: https://github.com/zxsa89675/ant-design-x-356/commit/a656b997c6d1e924b07117f31485d0d55db76f03.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by YumoImer** [comment]
This issue has been fixed and will be released in version 1.0.3.

**Comment by afc163** [comment]
@YumoImer 关联一下 PR

**Comment by YumoImer** [comment]
https://github.com/ant-design/x/pull/314
