### ISSUE TITLE
Sender组件能否支持焦点控制

### ISSUE THREAD

**Issue by zazzzf** [ant-design/x#360]
### 需求动机

[ant input methods](https://ant.design/components/input-cn#input-methods)
类似于antd input的method方法传入ref来控制焦点

### 提议的 API 是什么样的？
![image](https://github.com/user-attachments/assets/5fd45cc1-38e1-46b1-8aa6-42e96f9b9b2c)

_No response_

**Comment by zazzzf** [comment]
> 您希望 `Sender` 组件能够支持类似于 `antd Input` 组件的方法，通过传入 `ref` 来控制焦点。这是一个很好的建议，可以提升组件的可用性和灵活性。
> 
> 目前，`Sender` 组件可能没有直接支持这种功能。您可以尝试以下方法来实现：
> 
> 1. **使用 `ref` 获取组件实例**：通过 `React.createRef()` 或 `useRef()` 创建一个 `ref`，并将其传递给 `Sender` 组件。
> 2. **在组件内部实现焦点控制**：在 `Sender` 组件内部，您可以通过 `ref` 来访问 DOM 元素，并使用 `focus()` 方法来控制焦点。
> 
> 如果您希望这个功能能够被官方支持，您可以考虑在 ant-design/x 的 GitHub 仓库中提出一个功能请求（Feature Request）。如果您需要，我可以帮助您创建这个请求。
> 
> 如果您有其他问题或需要进一步的帮助，请随时告诉我！

请帮我创建需求

**Comment by YumoImer** [comment]
> 请帮我创建需求

感谢反馈，收到～
