### ISSUE TITLE
ThoughtChain样式问题

### ISSUE THREAD

**Issue by Moonquakesss** [ant-design/x#366]
### 重现步骤

在线示例链接：（必填）
https://x.ant.design/components/thought-chain-cn#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA

![image](https://github.com/user-attachments/assets/9f0a71c0-7118-4c28-9945-da9eb685ebd5)

### 版本

1.0.3

**Comment by YumoImer** [comment]
看起来是字体颜色的问题，查看下对应的标签样式，是否被覆盖了

**Comment by Moonquakesss** [comment]
> 看起来是字体颜色的问题，查看下对应的标签样式，是否被覆盖了

上面的图是从文档站中点进的Stackblitz中的运行 demo，我理解应该没有样式覆盖吧。

此外，我本地新起的项目也是同样的问题。
