### ISSUE TITLE
1.0.3版本的ThoughtChain样式问题

### ISSUE THREAD

**Issue by Moonquakesss** [ant-design/x#371]
### 重现步骤

在线示例链接：（必填）
https://x.ant.design/components/thought-chain-cn#%E4%BB%A3%E7%A0%81%E6%BC%94%E7%A4%BA
图1：![image](https://github.com/user-attachments/assets/82ef9420-f581-42c4-a7dc-27a67e7f3184)

图2：![image](https://github.com/user-attachments/assets/db92ca27-c2a4-4947-9c8f-29f8e861a075)

步骤：
图1.文档站中点击的 Stackblitz 中的运行 demo（无样式覆盖）
图2.本地新起项目，无样式覆盖，仍然存在样式问题

### 当前行为

1.0.3正式版本的ThoughtChain组件存在样式问题

### 预期行为

预期样式应该正常（经测试 1.0.0-alpha.2 样式是正常的）

### 版本

1.0.3

**Comment by YumoImer** [comment]
抱歉，这确实是个 bug ，我来跟进
