### ISSUE TITLE
Conversation组件可以考虑加一个resize属性

### ISSUE THREAD

**Issue by Shabi-x** [ant-design/x#381]
### 需求动机

Conversation组件主要用于实现侧边栏展示历史promt，可以考虑实现可拖动调整Conversation宽度的功能

### 提议的 API 是什么样的？

也许可以提供一个resize接口

**Comment by Shabi-x** [comment]
如果可以的话，我愿意尝试完成这个feature

**Comment by YumoImer** [comment]
感谢建议，但看起来这个功能使用 `antd` 的 [Splitter](https://ant-design.antgroup.com/components/splitter-cn) 组件配合 Conversation 组件就可以低成本完成。

**Comment by Shabi-x** [comment]
> 感谢建议，但看起来这个功能使用 `antd` 的 [Splitter](https://ant-design.antgroup.com/components/splitter-cn) 组件配合 `Conversations` 组件就可以低成本完成。
> 
> 目前 `Conversations` 会继承父元素的宽度。

感谢回复！学到了
