### ISSUE TITLE
Add tabIndex or autoFocus properties to `Sender` component for improved focus management

### ISSUE THREAD

**Issue by agatha197** [ant-design/x#382]
## Description
Currently, the `Sender` component lacks `tabIndex` and `autoFocus` properties, making it cumbersome to manage focus within the component programmatically. To achieve auto-focusing, I had to resort to using `querySelector`, which, while effective, is not the most clean or performant solution.

## Suggestion
It would be beneficial for performance and code cleanliness if the `Sender` component could support `tabIndex` or `autoFocus` properties out of the box. This would enable better focus management directly via props without the need for additional DOM manipulation.

## Expected Behavior
- The `Sender` component should accept `tabIndex` or `autoFocus` as props.
- When `autoFocus` is true, the component should automatically focus when it mounts.
- The `tabIndex` property should control the component's order in the tab navigation flow.

## Current Workaround
Currently, I am using `querySelector` to manually set focus to the `Sender` component, which is not ideal in terms of performance and code maintainability.

## Additional Context
Adding these properties would enhance the usability and accessibility of the `Sender` component, making it more versatile in various use cases.

**Comment by YumoImer** [comment]
Thanks! I expect to resolve this issue using `ref` in version 1.0.4.

duplicate: https://github.com/ant-design/x/issues/360
