### ISSUE TITLE
package.json中的构建命令不全，尝试使用legacy_dist命令构建失败，请问如何构建？

### ISSUE THREAD

**Issue by yusangeng** [ant-design/x#383]
### 重现步骤

1. dist命令package.json中其实没有。
2. legacy_dist命令运行失败，报错如下：
![image](https://github.com/user-attachments/assets/0abd99d0-4e7d-465f-b6a3-2762360cab8b)
![image](https://github.com/user-attachments/assets/43ad01ff-6b99-4df6-bf0f-0c0e0a079462)
zhu'yi注意，以上只是报错的两个例子，实际情况报错很多，但都是这两类之一。

### 版本

1.0.3

**Comment by YumoImer** [comment]
目前仓库是使用 `compile` 命令构建

**Comment by YumoImer** [comment]
- [ ] 更新 https://x.ant.design/docs/react/contributing-cn
- [ ] 更新 https://x.ant.design/docs/react/contributing
- [ ] 删除 package.json 中未被使用的、过期的命令
