### ISSUE TITLE
想问一下项目能实现这种自定义的Code Block的样式吗？

### ISSUE THREAD

**Issue by yecaiying** [ant-design/x#393]
### 需求动机

包括自定义 codeBlock 的样式，支持复制code等。
![image](https://github.com/user-attachments/assets/b88aef8b-c50c-4fe2-90be-2acffbf9672e)

**Comment by YumoImer** [comment]
Bubble 组件的 content 为 ReactNode，可以配合一些专门做 Code Block 渲染的包来实现该需求。

**Comment by yecaiying** [comment]
以stream的方式接收AI数据，每次接收一段新的消息时，是不是每次需要重生成一次code blcok的样式？

当前渲染的消息 = （之前接收的消息 + 最新接收的消息）

因为每次都需要将 **当前渲染的消息(Markdown)** 转为HTML。

**Comment by YumoImer** [comment]
> 以stream的方式接收AI数据，每次接收一段新的消息时，是不是每次需要重生成一次code blcok的样式？

这些问题需要看具体的包实现了，先暂时关闭了哈，有需要 reopen 即可。
