### ISSUE TITLE
useXAgent和XStream以及XRequest这三者使用场景的区别是什么？

### ISSUE THREAD

**Issue by Tzng** [ant-design/x#412]
### 需求动机

我现在有一个接口，可以返回流数据出来
```
  async function readStream(stream) {
    const reader = stream.getReader();
    const decoder = new TextDecoder(); // 如果流中是二进制数据，可以使用 TextDecoder 转换为字符串
    const result = ''; // 用于存储读取的结果
    try {
      while (true) {
        const { done, value } = await reader.read(); // 读取一块数据
        if (done) {
          console.log('流读取完成');
          break;
        }
        const msg = decoder.decode(value, { stream: true }); // 解码数据块
        console.log('msg', msg);
      }
    } finally {
      reader.releaseLock(); // 确保释放 reader 锁
    }
    return result;
  }
```
这个代码能打印出我每一次接受到的数据，我想问的是，我这个函数应该给useXAgent用还是给XStream还是给XRequest

我开始想到的是 可以用useXAgent中的onUpdate来用，但是没有效果，那我应该使用XStream来做吗。

但是我看XStream的demo只是给一个Bubble 用，我怎么在Bubble.List中使用

```
    <Bubble.List
      items={items.length > 0 ? items : [{ content: placeholderNode, variant: 'borderless' }]}
      roles={roles}
      className={styles.messages}
    />
```

难道我直接去修改这个items中的文字吗，这样会不会感觉很奇怪

### 提议的 API 是什么样的？

有一个前后端结合的Demo参考

**Comment by Tzng** [comment]
也就是说，我想在消息列表中渲染出我接收到的流数据：

        <Bubble.List
          items={items.length > 0 ? items : [{ content: placeholderNode, variant: 'borderless' }]}
          roles={roles}
          className={styles.messages}
        />

**Comment by YumoImer** [comment]
> 我想问的是，我这个函数应该给 useXAgent 用还是给 XStream 还是给 XRequest

看起来 `readStream` 这个函数做的事情和 `XStream` 类似，所以不应该使用 `XStream`。

`XRequest` 内部使用了 `XStream` 做流解析，所以不应该使用 `XRequest`。

所以感觉你的 `readStream` 函数应该配合一个 `fetch` 请求来自定义 `useXAgent` 的  `reuqest`，可以参考 [components-use-x-agent-demo-custom](https://x.ant.design/components/use-x-agent-cn#components-use-x-agent-demo-custom) 来自定义你的请求。
