### ISSUE TITLE
请问可以与antd4.x    react 17 一起用吗

### ISSUE THREAD

**Issue by kxcy001123** [ant-design/x#429]
### 需求动机

公司基础组件库是基于react17的，不知道会不会有兼容性问题

**Comment by kxcy001123** [comment]
我想知道的是antdx 可以与 antd4.x、react 17 一起使用吗

**Comment by afc163** [comment]
@YumoImer 官方给个明确的答复？

**Comment by YumoImer** [comment]
不可以，Ant Design X 对 `antd` 最低版本要求为 `5.x`，对 `react` 最低版本要求为 `18.x`。

**Comment by YumoImer** [comment]
由于群里有同学问一样的问题，我以为是同一个人，不过看起来应该在 issues 里回复，不好意思～

![image](https://github.com/user-attachments/assets/a82d4d33-ce01-45c8-a001-e8a092754717)

**Comment by whinc** [comment]
能否学习 ProComponents，继续支持 antd v4 的最新版本，目前 antd v4 存在大量的存量项目，这部分希望不要被舍弃，给予足够的迁移时间。

**Comment by JunlinZhu-Tommy** [comment]
antd v5是可以用react 17的，能否在antd x 里面也帮忙支持react 17呢？
